### ISSUE TITLE
Having trouble with quick start

### ISSUE THREAD

**Issue by byronka** [bee-software/kickstart#1]
I tried following the quick start but ran into issues.  I've tried this on Windows and Mac so far without success. 

From my recent try on Mac:

Using a Macbook pro M1 chip
OpenJDK Java 21 is on the path

When I run the first step to start a Postgres container, it starts up fine, on both Windows and Mac - no surprise there. 

When I run make build, it fails.  Sending the console output by email.

**Comment by testinfected** [comment]
Strange, I don't run into this issue. Let me investigate a bit further.

**Comment by testinfected** [comment]
Hum, cannot reproduce on my side. I don't get why you get a permission error on the database when flyway migrations run.

**Comment by testinfected** [comment]
I could reproduce by removing my docker volume and starting anew. I'll have to investigate

**Comment by byronka** [comment]
state. the cause and solution to all life’s problems

**Comment by testinfected** [comment]
Should be fixed by now
